### ISSUE TITLE
Test a large batch upload to check all assets go up with script

### ISSUE THREAD

**Issue by kemiljk** [kemiljk/better-logos-figma#11]
1. Move current images to a Test media folder
2. Upload a whole batch
3. If it works, delete the Test folder

**Comment by kemiljk** [comment]
@neefrehman I've got all assets for Logotypes exported from Figma and in folders etc to follow our structure. When I run the `npm run upload:assets` I get the following error but I can't see a hidden `.DS_Store` file inside `./assets`. Any idea?

```
~/GitHub/better-logos-figma(main*) » npm run upload:assets  karlkoch@K-MBP

> Better-Logos@1.0.0 upload:assets
> node --experimental-specifier-resolution node --loader ts-node/esm scripts/upload-assets.ts

(node:13099) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
error uploading logos: Error: ENOTDIR: not a directory, scandir './assets/.DS_Store'
    at Module.readdirSync (node:fs:1072:3)
    at file:///Users/karlkoch/GitHub/better-logos-figma/scripts/upload-assets.ts:76:33
    at Array.reduce (<anonymous>)
    at getLogosFromFs (file:///Users/karlkoch/GitHub/better-logos-figma/scripts/upload-assets.ts:74:32)
    at main (file:///Users/karlkoch/GitHub/better-logos-figma/scripts/upload-assets.ts:148:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -20,
  syscall: 'scandir',
  code: 'ENOTDIR',
  path: './assets/.DS_Store'
}
```

**Comment by neefrehman** [comment]
ah it only gets generated on some computers depending on some git stuff I think. let me filter it out in the function :)

**Comment by neefrehman** [comment]
just pushed an update @kemiljk. can you try now?

**Comment by kemiljk** [comment]
Ah weird, it went away first time but I got another error then it happened again when I tried @neefrehman

**Comment by kemiljk** [comment]
This was the other error I got first before the `.DS_Store` one again
```
---------------------------------------------------------------------------
~/GitHub/better-logos-figma(main*) » npm run upload:assets  karlkoch@K-MBP

> Better-Logos@1.0.0 upload:assets
> node --experimental-specifier-resolution node --loader ts-node/esm scripts/upload-assets.ts

(node:14330) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
error uploading logos: Error: Company Andreessen Horowitz extracted AndValidate Andreessen Horowitz_logo_(Black).svg does not match Andreesson Horowitz from folder
    at extractLogoDataAndValidateFilename (file:///Users/karlkoch/GitHub/better-logos-figma/scripts/upload-assets.ts:61:11)
    at file:///Users/karlkoch/GitHub/better-logos-figma/scripts/upload-assets.ts:105:11
    at Array.map (<anonymous>)
    at file:///Users/karlkoch/GitHub/better-logos-figma/scripts/upload-assets.ts:100:38
    at Array.reduce (<anonymous>)
    at getLogosFromFs (file:///Users/karlkoch/GitHub/better-logos-figma/scripts/upload-assets.ts:96:30)
    at main (file:///Users/karlkoch/GitHub/better-logos-figma/scripts/upload-assets.ts:175:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by kemiljk** [comment]
Oh I see the error with the above one now haha! But DS_Store is back still

**Comment by kemiljk** [comment]
Okay, making progress here, there were some errors with my file naming/folders etc in a few places. It was my fault. It's working now!

**Comment by kemiljk** [comment]
@neefrehman processing the full batch of logotypes now I've got them all foldered and sorted properly, we'll soon see if it's worked!
